name: Docker

on:
  watch:
    types: started

env:
  # 设置 docker 镜像名
  IMAGE_NAME: zzcabc/ddtv
  REPO_URL: https://github.com/CHKZL/DDTV2
  REPO_BRANCH: master
  DOCKER_FILE: config/Dockerfile
  TZ: Asia/Shanghai

jobs:
  Build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        run: |
          sudo -E wget -qq https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo -E dpkg -qq  sudo dpkg -i packages-microsoft-prod.deb
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install -y apt-transport-https
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install -y git dotnet-sdk-5.0
          sudo -E apt-get -qq clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      - name: Clone Source Code
        run: |
          df -hT $PWD
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH ddtv

      - name: Build Source
        run: |
          cd ddtv
          cd DDTVLiveRec
          dotnet publish -c Release /p:DebugType=None




  #push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # 构建镜像，指定镜像名
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
        # 登录到 dockerhub，使用 GitHub secrets 传入账号密码，密码被加密存储在 GitHub 服务器，添加方法见下图。
      - name: Log into registry
        run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u libra146 --password-stdin

      - name: Push image
        run: |
          # 拼接镜像 id，这个镜像 id 就是在使用 docker 镜像时 pull 后面的名字。
          IMAGE_ID=libra146/$IMAGE_NAME

          # 将所有的大写字母转为小写
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # 从 GitHub.ref 中取出版本
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # 从 tag 名字中替换 v 字符
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          # 设置镜像 id 和版本号
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          # 进行 push
          docker push $IMAGE_ID:$VERSION
