name: Docker

on:
  watch:
    types: started

env:
  # 设置 docker 镜像名
  IMAGE_NAME: zzcabc/ddtv
  REPO_URL: https://github.com/CHKZL/DDTV2
  REPO_BRANCH: master
  DOCKER_FILE: config/Dockerfile
  TZ: Asia/Shanghai
  UPLOAD_RELEASE: true

jobs:
  Build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        run: |
          sudo wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
          sudo apt-get update
          sudo apt-get install -y git dotnet-sdk-5.0 docker-ce docker-ce-cli containerd.io
          sudo apt-get clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      - name: Clone Source Code
        run: |
          df -hT $PWD
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH ddtv

      - name: Build Source
        run: |
          cd ddtv
          cd DDTVLiveRec
          dotnet publish -c Release /p:DebugType=None

      - name: Docker Build
        run: |
          cd /home/runner/work/ddtv_bulid/ddtv_bulid/ddtv/DDTVLiveRec/bin/Release
          docker build . --file $DOCKER_FILE --tag $IMAGE_NAME:LA

      - name: Log into registry
        run: |
          docker login -u zzcabc --password-stdin zzc19990105.
      
      - name: Push image
        run: |
          docker push $IMAGE_NAME:latest




