name: Docker

on:
  watch:
    types: started

env:
  # 设置 docker 镜像名
  IMAGE_NAME: zzcabc/ddtv
  REPO_URL: https://github.com/CHKZL/DDTV2
  REPO_BRANCH: master
  DOCKER_FILE: config/Dockerfile
  TZ: Asia/Shanghai
  UPLOAD_RELEASE: true

jobs:
  Build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        run: |
          sudo wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo apt-get update
          sudo apt-get install -y git dotnet-sdk-5.0
          sudo apt-get clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      - name: Clone Source Code
        run: |
          df -hT $PWD
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH ddtv

      - name: Build Source
        run: |
          cd ddtv
          cd DDTVLiveRec
          dotnet publish -c Release /p:DebugType=None
