name: Docker_Test

on:
  watch:
    types: started

env:
  # 设置 docker 镜像名
  REPO_URL: https://github.com/CHKZL/DDTV2
  REPO_BRANCH: master
  IMAGE_NAME: zzcabc/ddtv
  RELEASE_PATH: ddtv/DDTVLiveRec/bin/Release/net5.0
  TZ: Asia/Shanghai
  UPLOAD_RELEASE: true

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Initialization Environment
        run: |
          sudo wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y apt-transport-https git dotnet-sdk-5.0

      - name: Clone Source Code
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH ddtv

      - name: Build Source
        run: |
          mkdir -p $RELEASE_PATH
          cp $DOCKER_FILE $RELEASE_PATH/Dockerfile
          cd ddtv/DDTVLiveRec
          sudo dotnet publish -c Release /p:DebugType=None
      - name: Run Buildx
        run: |
          cd ddtv/DDTVLiveRec/bin/Release/net5.0
          echo -e "FROM mcr.microsoft.com/dotnet/aspnet:5.0" > Dockerfile
          echo -e "WORKDIR /DDTVLiveRec" > Dockerfile
          echo -e "RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone" > Dockerfile
          echo -e "COPY ./publish /DDTVLiveRec"  > Dockerfile
          echo -e "EXPOSE 11419" > Dockerfile
          echo -e "VOLUME /DDTVLiveRec/tmp"  > Dockerfile
          echo -e "VOLUME /DDTVLiveRec/BiliUser.ini"  > Dockerfile
          echo -e "VOLUME /DDTVLiveRec/RoomListConfig.json"  > Dockerfile
          echo -e "ENTRYPOINT [\"dotnet\", \"DDTVLiveRec.dll\"]"  > Dockerfile
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            -t zzcabc/ddtv .