name: Docker_Test

on:
  watch:
    types: started

env:
  # 设置 docker 镜像名
  REPO_URL: https://github.com/CHKZL/DDTV2
  REPO_BRANCH: master
  DOCKER_FILE: config/Dockerfile
  TZ: Asia/Shanghai
  UPLOAD_RELEASE: true

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Initialization Environment
        run: |
          sudo wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y apt-transport-https git dotnet-sdk-5.0

      - name: Clone Source Code
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH ddtv

      - name: Build Source
        run: |
          mkdir -p ddtv/DDTVLiveRec/bin/Release/net5.0
          cp config/Dockerfile ddtv/DDTVLiveRec/bin/Release/net5.0/Dockerfile
          cd ddtv/DDTVLiveRec
          sudo dotnet publish -c Release /p:DebugType=None
      - name: Run Buildx
        run: |
          cd bin/Release/net5.0
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            -t zzcabc/ddtv .