name: Docker_Test

on:
  watch:
    types: started

env:
  # 设置 docker 镜像名
  REPO_URL: https://github.com/CHKZL/DDTV2
  REPO_BRANCH: master
  DOCKER_FILE: config/Dockerfile
  TZ: Asia/Shanghai
  UPLOAD_RELEASE: true

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        run: |
          sudo wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y apt-transport-https git dotnet-sdk-5.0
          sudo curl -fsSL https://get.docker.com -o get-docker.sh
          sudo chmod 777 get-docker.sh
          sudo sh get-docker.sh
          sudo apt-get clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      - name: Open Docker Buildx
        run: |
          echo -e "{" > /etc/docker/daemon.json
          echo -e "\t\"experimental\": true" > /etc/docker/daemon.json
          echo -e "}" > /etc/docker/daemon.json
      - name: Restart Docker
        run: |
          sudo systemctl restart docker
          sudo docker info | grep -i exp

          
      