name: Docker_Test

on:
  watch:
    types: started

env:
  # 设置 docker 镜像名
  REPO_URL: https://github.com/CHKZL/DDTV2
  REPO_BRANCH: master
  DOCKER_FILE: config/Dockerfile
  TZ: Asia/Shanghai
  UPLOAD_RELEASE: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        run: |
          sudo wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y apt-transport-https git dotnet-sdk-5.0
          sudo curl -fsSL https://get.docker.com -o get-docker.sh
          sudo chmod 777 get-docker.sh
          sudo sh get-docker.sh
          sudo apt-get clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo systemctl restart docker

      - name: Clone Source Code
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH ddtv

      - name: Build Source
        run: |
          mkdir -p ddtv/DDTVLiveRec/bin/Release/net5.0
          sudo cp config/Dockerfile ddtv/DDTVLiveRec/bin/Release/net5.0/Dockerfile
          cd ddtv/DDTVLiveRec
          sudo dotnet publish -c Release /p:DebugType=None

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker Buildx (build)
        run: |
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --output "type=image,push=false" \
            --tag zzcabc/ddtv:latest \
            --file ./Dockerfile ./


          
      