name: Docker_Build_Test

on:
  watch:
    types: started

env:
  # 设置 docker 镜像名
  REPO_URL: https://github.com/CHKZL/DDTV2
  REPO_BRANCH: master
  DOCKER_FILE: config/Dockerfile
  IMAGE_NAME: zzcabc/ddtv:amd64
  RELEASE_PATH: ddtv/DDTVLiveRec/bin/Release/net5.0
  TZ: Asia/Shanghai
  UPLOAD_RELEASE: true

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        run: |
          sudo wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo curl -fsSL https://get.docker.com -o get-docker.sh
          sudo chmod 777 get-docker.sh
          sudo sh get-docker.sh
          sudo apt-get install -y apt-transport-https git dotnet-sdk-5.0
          sudo apt-get clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo systemctl restart docker

      - name: Clone Source Code
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH ddtv

      - name: path
        run: |
          pwd
          ls
          cd etc
          pwd
          ls
          cd docker
          pwd
          ls
          
      





