name: Docker

on:
  watch:
    types: started

env:
  # 设置 docker 镜像名
  REPO_URL: https://github.com/CHKZL/DDTV2
  REPO_BRANCH: master
  DOCKER_FILE: config/Dockerfile
  TZ: Asia/Shanghai
  UPLOAD_RELEASE: true

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        run: |
          sudo wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y apt-transport-https git dotnet-sdk-5.0
          sudo curl -fsSL https://get.docker.com -o get-docker.sh
          sudo chmod 777 get-docker.sh
          sudo sh get-docker.sh
          sudo apt-get clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo systemctl restart  docker

      - name: Clone Source Code
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH ddtv

      - name: Build Source
        run: |
          mkdir -p ddtv/DDTVLiveRec/bin/Release/net5.0
          cp config/Dockerfile ddtv/DDTVLiveRec/bin/Release/net5.0/Dockerfile
          cd ddtv/DDTVLiveRec
          sudo dotnet publish -c Release /p:DebugType=None

      - name: Build Docker Iamge
        run: |
          cd ddtv/DDTVLiveRec/bin/Release/net5.0
          sudo docker build -t $IMAGE_NAME:latest .

      - name: Log into registry
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push $IMAGE_NAME:latest
          
      





